services:
  # Development service with hot reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Production service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped

  # Test service
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=test
      - PYTHONPATH=/app
    command: poetry run pytest -v --cov=app

  # Frontend development service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - app-dev 