apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: fastapi-todo
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-todo
      component: api
  template:
    metadata:
      labels:
        app: fastapi-todo
        component: api
    spec:
      containers:
      - name: api
        image: fastapi-todo-api
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database-url
        - name: API_V1_STR
          value: /api/v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 