apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-deployment.yaml
- api-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- postgres-statefulset.yaml
- postgres-service.yaml
- ingress.yaml
- github-actions-sa.yaml

patchesStrategicMerge:
- images-patch.yaml

commonLabels:
  app: fastapi-todo

configMapGenerator:
- name: app-config
  literals:
  - API_V1_STR=/api/v1

secretGenerator:
- name: db-credentials
  literals:
  - username=postgres
  - password=changeme
  - database-url=postgresql://postgres:changeme@postgres:5432/fastapi_todo 