apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-todo-dev

resources:
- ../../base
- namespace.yaml

patches:
- target:
    kind: Deployment
    name: api
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi

- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - ENVIRONMENT=development

secretGenerator:
- name: db-credentials
  behavior: merge
  literals:
  - password=dev-password

labels:
- pairs:
    environment: development 